name: 'Setup API'
description: 'Setup Go, télécharge les dépendances, installe swag et génère les docs Swagger'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: api/go.mod
        cache-dependency-path: api/go.sum

    - name: Téléchargement des dépendances
      shell: bash
      run: cd api && go mod download

    - name: Installation swag
      shell: bash
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Génération des docs Swagger
      shell: bash
      run: make swag
