// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bibliotheque-front/internal/models"
	"bibliotheque-front/internal/session"
	"fmt"
)

func NouvelExemplaire(livre models.Livre, user *session.User, errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center\"><div class=\"col-md-8 col-lg-7\"><nav aria-label=\"breadcrumb\" class=\"mb-3\"><ol class=\"breadcrumb\"><li class=\"breadcrumb-item\"><a href=\"/\">Catalogue</a></li><li class=\"breadcrumb-item active\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(livre.Titre)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/nouveau_exemplaire.templ`, Line: 16, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</li></ol></nav><div class=\"card shadow-sm\"><div class=\"card-header bg-dark text-white fw-bold\">Ajouter un exemplaire — ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(livre.Titre)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/nouveau_exemplaire.templ`, Line: 21, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"card-body p-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if errMsg != "" {
				templ_7745c5c3_Err = Alert("danger", errMsg).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"POST\" action=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 templ.SafeURL
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/admin/livres/%d/exemplaires", livre.ID)))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/nouveau_exemplaire.templ`, Line: 29, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><div class=\"row g-3 mb-3\"><div class=\"col-md-6\"><label for=\"code_barre\" class=\"form-label\">Code barre <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control font-monospace\" id=\"code_barre\" name=\"code_barre\" required></div><div class=\"col-md-6\"><label for=\"caution\" class=\"form-label\">Caution (€) <span class=\"text-danger\">*</span></label> <input type=\"number\" class=\"form-control\" id=\"caution\" name=\"caution\" min=\"0\" step=\"0.01\" required></div></div><h6 class=\"mb-2\">Emplacement</h6><div class=\"row g-3 mb-4\"><div class=\"col-md-4\"><label for=\"travee\" class=\"form-label\">Travee <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" id=\"travee\" name=\"travee\" placeholder=\"Ex : A\" required></div><div class=\"col-md-4\"><label for=\"etagere\" class=\"form-label\">Etagere <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" id=\"etagere\" name=\"etagere\" placeholder=\"Ex : 3\" required></div><div class=\"col-md-4\"><label for=\"niveau\" class=\"form-label\">Niveau <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" id=\"niveau\" name=\"niveau\" placeholder=\"Ex : 2\" required></div></div><div class=\"d-flex gap-2\"><button type=\"submit\" class=\"btn btn-dark\">Enregistrer</button> <a href=\"/\" class=\"btn btn-outline-secondary\">Annuler</a></div></form></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Ajouter un exemplaire", user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
