// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Register(errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center\"><div class=\"col-sm-10 col-md-8 col-lg-6\"><div class=\"card shadow-sm\"><div class=\"card-header bg-dark text-white text-center fw-bold\">Creer un compte</div><div class=\"card-body p-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if errMsg != "" {
				templ_7745c5c3_Err = Alert("danger", errMsg).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<form method=\"POST\" action=\"/register\"><div class=\"row g-3\"><div class=\"col-md-6\"><label for=\"prenom\" class=\"form-label\">Prenom</label> <input type=\"text\" class=\"form-control\" id=\"prenom\" name=\"prenom\" required></div><div class=\"col-md-6\"><label for=\"nom\" class=\"form-label\">Nom</label> <input type=\"text\" class=\"form-control\" id=\"nom\" name=\"nom\" required></div><div class=\"col-12\"><label for=\"email\" class=\"form-label\">Adresse email</label> <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"nom@exemple.com\" required></div><div class=\"col-12\"><label for=\"mot_de_passe\" class=\"form-label\">Mot de passe</label> <input type=\"password\" class=\"form-control\" id=\"mot_de_passe\" name=\"mot_de_passe\" minlength=\"8\" required><div class=\"form-text\">Minimum 8 caracteres.</div></div><div class=\"col-12\"><label for=\"adresse\" class=\"form-label\">Adresse postale</label> <input type=\"text\" class=\"form-control\" id=\"adresse\" name=\"adresse\" required></div><div class=\"col-md-6\"><label for=\"caution_initiale\" class=\"form-label\">Caution initiale (€)</label> <input type=\"number\" class=\"form-control\" id=\"caution_initiale\" name=\"caution_initiale\" min=\"0\" step=\"0.01\" required></div></div><div class=\"d-grid mt-4\"><button type=\"submit\" class=\"btn btn-dark\">Creer mon compte</button></div></form></div><div class=\"card-footer text-center text-muted small\">Deja inscrit ? <a href=\"/login\">Se connecter</a></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Inscription", nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
