name: API - Audit sécurité

on:
  workflow_call:
  workflow_dispatch:

jobs:
  audit:
    name: Audit des dépendances
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-api
      - name: Installation govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Audit
        run: make vuln-api
