name: API - Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-api
      - name: Build
        run: make build-api
