name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  # ── Orchestration API ───────────────────────────────────────────────────────
  ci-api:
    name: CI - API
    uses: ./.github/workflows/ci-api.yml

  # ── Orchestration Frontend ──────────────────────────────────────────────────
  ci-front:
    name: CI - Frontend
    uses: ./.github/workflows/ci-front.yml

  # Release et publication docker si les tests sont passés
  release:
    name: Release
    needs: [ci-api, ci-front]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/release.yml

  docker-publish:
    name: Publication Docker
    needs: [ci-api, ci-front, release]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/docker-publish.yml
    with:
      version: ${{ needs.release.outputs.tag }}
