name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # ── Orchestration API ───────────────────────────────────────────────────────
  ci-api:
    name: CI - API
    uses: ./.github/workflows/ci-api.yml

  # ── Orchestration Frontend ──────────────────────────────────────────────────
  ci-front:
    name: CI - Frontend
    uses: ./.github/workflows/ci-front.yml

  playwright:
    name: Tests Playwright
    uses: ./.github/workflows/playwright.yml
