name: Release

on:
  workflow_call:
    outputs:
      tag:
        description: "Tag de la release"
        value: ${{ jobs.release.outputs.tag }}
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Créer une release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6.0.3

      - name: Créer la release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
